### ISSUE TITLE
Request for Detailed System Specifications for Emulator Development

### ISSUE THREAD

**Issue by Andpuv** [WilliamBattsIII/doubleword#1]
Hello! I hope this is the right section for this type of request; if not, I apologize. I’d love to contribute to this project by working on the emulator, but I noticed that the system specifications aren’t fully detailed yet. Could you provide some guidance on the intended design specifications? Here are a few questions that would help establish a foundation for the emulator:

- **Instruction Set Design:** Is this intended as a RISC, CISC, or custom instruction set? Based on the drafts, it appears RISC, but clarification would be helpful.

- **Privilege Levels:** Will the CPU need to support privilege levels (e.g., user vs. kernel mode)?

- **User/Kernel Mode Switching:** Should there be dedicated instructions for switching between user and kernel modes?

- **Memory Layout:** Do you have any specific memory layout or segmentation model in mind?

- **Read/Write Operations:** How should read/write operations be handled? (For instance, would you like to emulate write-back buffers, caches, or any form of memory fencing?)

- **I/O Operations:** Should I/O be memory-mapped, or will it use a separate address space (like port-based I/O)?

- **Interrupt Handling:** How should the CPU handle asynchronous events (e.g., interrupts from external devices)?

- **Exception and Trap Handling:** What is the expected handling mechanism for synchronous events (e.g., exceptions, traps, software interrupts)? Are there specific types of exceptions that should be standardized (e.g., divide-by-zero, overflow, invalid instruction)?

- **ISA Extensions:** Would you like the instruction set to support future extensions?

- **Co-processor Support:** Should the CPU design allow for co-processors (e.g., for floating-point operations or I/O management)?

Thanks for considering these questions, and I apologize for the extensive list! These details will really help in building a meaningful emulator for the project.

Looking forward to contributing to this project!

**Comment by WilliamBattsIII** [comment]
Hi, there!
I'm glad to hear that other people are interested in this project. I'm currently in the process of finishing the ISA and specifications for the processor - so some of these might change. (they probably won't, but they could)

Anyways, the documentation lists support for a _few_ of these things, but not all of them. I'm designing this architecture to lean more towards the RISC-y side of things. I'll make this more clear once I'm done with the documentation and drafts, and once I have the time to put together a more fancy manual.

As for privilege levels, they are supported. In the System Control Register, a bit stores the current privilege level - although you can't actually write to this register, it is there.

The CPU itself maintains the Memory Access Table, which is a bitmap of privileged and non-privileged blocks of memory. It's not anything as complex as you might see in other architectures, but it fulfills my needs - that is, as a rudimentary sort of memory protection.
Certain instructions need a Supervisor privilege level, but most don't.
Interrupt handlers are run in supervisor-mode, as does the CPU on first boot. You can use the IRET instruction to move back to user mode - if the return address on the stack is in unprivileged memory. (I haven't pushed the commit for this documentation change yet, but this also means that all memory is marked as privileged on boot to prevent accidentally dropping down into user mode)

With interrupts, there is a set of interrupts listed in the documentation that are specifically noted to be used for interrupt handling. There are certain standardized errors, like with invalid instructions, unaligned memory accesses, and privilege mismatching. Overflows actually just trigger a certain ALU flag in the System Control Register.

For ISA extensions, I am considering this in the future, depending on what comes up. It likely won't be anything major - that would probably come as part of a redesign, or "second generation" Doubleword processor.
At this point in time, I'm debating coprocessors. I'm considering making the graphics/video subsystem extensive enough to render simple shapes - it would prove complex enough to count as a coprocessor, I suppose. As for floating point, I'm not entirely against supporting it. It's probably the most likely scenario for if I were to ever add a coprocessor to doubleword.

I/O is primarily port-based, but it is memory-mapped to an extent. Hard drive accesses read to and write from a certain buffer in memory. (the location of the buffer is configured over port-based I/O) The same thing goes for the video system, which I haven't yet written documentation for. At this point in time, I'm leaning more towards the side of having a memory-mapped video buffer.

With the memory layout and read/write operations, I'm not going for any sort of multi-processor emulation or any timing-specific/cycle-specific emulation. As such, no fencing - and I'm also not doing caches, as it's a situation where all memory accesses are seen by the emulated CPU as happening more-or-less instantly, eliminating the need for a cache.
As I mentioned above, I'm not planning to emulate multi-processor scenarios. I don't have much knowledge or experience of the topic yet, although I hope to put together a more advanced iteration someday which will be designed with these things in mind.

The memory layout is yet to be properly documented, but it's fairly simple. From the point of view of the operating system, the memory map is nearly unlimited. There's a little bit of space earmarked for firmware at the bottom of the memory space (near 0x00000000), and disabled-by-default blocks of memory that you can move around - these are things like memory-mapped hard drive or video accesses, as well as the MAT.

Finally, to cover interrupts in more detail, I'm planning to have a buffer of interrupts that will fill up if incoming ones aren't dealt with in time. I have yet to actually document this. There is a table in memory called the Interrupt Vector Table, describing the locations of interrupt handlers. It's not terribly big: at 4 bytes per memory address and 256 interrupt vectors, it's just 1 kilobyte.

I hope all of this clarified things a little bit - I want to thank you for your interest in this project. Currently, the emulator and documentation are in a very unfinished state - moreso the emulator. Despite this, if you have anything to add or comment on, I'd love to hear from you!

**Comment by WilliamBattsIII** [comment]
One more thing -- I'll get to completing the documentation as quick as possible, so you and anyone else who would like to contribute has a solid starting point to work off of.

**Comment by Andpuv** [comment]
Hi, there!

Thank you so much for the detailed response. It's great to have more clarity on the design so far. I'm definitely looking forward to seeing the finalized documentation once it's ready.

In the meantime, I'll start thinking about the general structure for the emulator and how to approach the different components based on the specifications you've outlined. I understand the current state of the emulator is still evolving, and I'll hold off on deep implementation work until the documentation is more complete.

See you soon!

**Comment by WilliamBattsIII** [comment]
Wanted to add a small update - I've been busy with, well, life - but I haven't forgotten about this project!

Sorry to keep you waiting for so long - over the next couple months, I'll try to complete documentation on the architecture (as well as re-learn it)
The state of the emulator/architecture will probably go through some big changes - nothing is final yet, but I'll let you know when it is.

Thank you for your interest in this project!

**Comment by Andpuv** [comment]
Hi William,

Thank you for the update! I completely understand that life can get busy, and I appreciate you taking the time to let me know about your plans for the project. No worries at all—there's no rush, and I’m just happy to know you’re still thinking about it.

I’m really looking forward to seeing the documentation whenever it’s ready, and I’m excited to contribute when the time comes. In the meantime, if there’s anything small I can help with or if you’d like any feedback on changes, please don’t hesitate to reach out.

Thanks again for your hard work on this, and take care!
